### ISSUE TITLE
Multiline textfield must be supported

### ISSUE THREAD

**Issue by kunalgupta1593** [AzimoLabs/SMFloatingLabelTextField#3]

**Comment by matkuznik** [comment]
Are you talking about UITextView?

**Comment by kunalgupta1593** [comment]
I am talking about changing the frame of a textfield so that it can give a look just like textView , in case some developer has to show multiline then he would be using text view and that would not show this kind of animation in which placeholder moves up. So my idea is to make the UI uniform by integrating textview like features in textfield. as done in this library
# **https://github.com/jobandtalent/AnimatedTextInput**

**Comment by matkuznik** [comment]
If you look at implementation of AnimatedTextInput lib then you realise that "Multiline Text View" is an subclass of `UITextView`.

Unfortunately changing the frame is not enough because `UITextField` contains `UITextFieldLabel` which is subclass of `UILabel` and
`numberOfLines` is set to `1`.

The approach used in `AnimatedTextInput` is good as soon as you don't care about all features that storyboards give you for free (views needs to inherit from `UIView`).

IMHO the better approach would be to create another library just for this.
